### ISSUE TITLE
Error when saving without ".shp"

### ISSUE THREAD

**Issue by KarzoKalori** [j3r3m1/gen_buildveg_vlayers#1]
Nothing unusual, but it can be convenient that the tool creates two shape files as output from start without the user having to write ".shp" after the name.

![spara shp](https://user-images.githubusercontent.com/83512843/202410794-4f5ce4b3-668d-42b9-8570-3927b72e5a1c.jpg)

**Comment by j3r3m1** [comment]
You are right.
By default I would rather go for .geojson if we need a default format but for now I would leave it as it is and the user can choose what suits him best.
